---
title: "COVID-19"
author: "Ethan Tenison"
date: "3/22/2020"
output: html_document
---

```{r libraries_data, message=FALSE}

library(tidyverse)
library(RCurl)
library(janitor)
library(sjmisc)
library(reshape2)
library(lubridate)
library(sf)
library(raster)
library(dplyr)


 download.file("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/archived_data/archived_time_series/time_series_19-covid-Confirmed_archived_0325.csv", destfile = "timeseries.csv", method = "curl")

ts <- read_csv("timeseries.csv")
ts <- clean_names(ts)

```

```{r states}

states <- ts %>% dplyr::filter(country_region == "US") %>% dplyr::filter(!str_detect(province_state, ",")) %>% dplyr::filter(province_state != c("Diamond Princess", "Grand Princess")) %>% dplyr::select(-country_region)

states <- states[c(1:3, 52:65)]

states <- melt(states, id.vars = c("province_state", "lat","long"))
states$variable <- gsub( "x", "", states$variable)
states$variable <- mdy(states$variable)
states <- rename(states, Date = variable, Confirmed_Cases = value)
states <- filter(states, province_state != "Virgin Islands")

write.csv(states, "states.csv")


```


```{r tx}

texas <- ts %>% dplyr::filter(country_region == "US") %>% dplyr::filter(str_detect(province_state, ", TX"))


```